apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  ROOT_PASSWORD: senha123
  MYSQL_DATABASE: meubanco
  // secrets devem ser executadas previamente no cluster kubernetes 
  // e não devem ser colocadas no github , esse arquivo está aqui só como um exemplo!
